server:
  port: 10001

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:jimmyseraph/tyloo-configures.git
  profiles:
    active: dev, local, test

  security:
    user:
      name: liudao
      password: 123456